packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
minimumReleaseAgeExclude:
  - '@neuralfog/elemix@0.9.4'
  - '@neuralfog/hydris@0.9.4'
  - '@neuralfog/elemix-analyzer-darwin-arm64@0.9.4'
  - '@neuralfog/elemix-analyzer-darwin-x64@0.9.4'
  - '@neuralfog/elemix-analyzer-linux-arm64@0.9.4'
  - '@neuralfog/elemix-analyzer-linux-x64@0.9.4'
  - '@neuralfog/elemix-analyzer-win32-arm64@0.9.4'
  - '@neuralfog/elemix-analyzer-win32-x64@0.9.4'
  - '@neuralfog/elemix-analyzer@0.9.4'
  - '@neuralfog/elemix-template-formatter-darwin-arm64@0.9.4'
  - '@neuralfog/elemix-template-formatter-darwin-x64@0.9.4'
  - '@neuralfog/elemix-template-formatter-linux-arm64@0.9.4'
  - '@neuralfog/elemix-template-formatter-linux-x64@0.9.4'
  - '@neuralfog/elemix-template-formatter-win32-arm64@0.9.4'
  - '@neuralfog/elemix-template-formatter-win32-x64@0.9.4'
  - '@neuralfog/elemix-template-formatter@0.9.4'
  - '@neuralfog/elemix-compiler-darwin-arm64@0.9.4'
  - '@neuralfog/elemix-compiler-darwin-x64@0.9.4'
  - '@neuralfog/elemix-compiler-linux-arm64@0.9.4'
  - '@neuralfog/elemix-compiler-linux-x64@0.9.4'
  - '@neuralfog/elemix-compiler-win32-arm64@0.9.4'
  - '@neuralfog/elemix-compiler-win32-x64@0.9.4'
  - '@neuralfog/elemix-compiler@0.9.4'
  - '@neuralfog/elemix-ssr-plugin@0.9.4'
  - '@types/pg@8.23.1'
