packages:
  - 'packages/*'
overrides:
  '@neuralfog/elemix-template-formatter-linux-x64': 'link:../elemix/packages/formatter/npm/linux-x64'
allowBuilds:
  '@parcel/watcher': false
minimumReleaseAge: 0
